version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: frontend-feedKU
    command: /bin/sh -c "while sleep 1000; do :; done"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - protocol: tcp
        published: 8080
        target: 8080
    volumes:
       - ./frontend:/root/frontend:cached
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: backend-feedKU
    command: /bin/sh -c "while sleep 1000; do :; done"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - protocol: tcp
        published: 8000
        target: 8000
    volumes:
      - ./backend:/root/backend:cached
    