# Generated by Django 4.1.3 on 2022-11-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userPost', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200000)),
            ],
        ),
    ]
